services:

  mysql:
    image: mysql:8.0
    container_name: college_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: moki@amma123
      MYSQL_DATABASE: college_admission
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - college_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmoki@amma123"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Backend/college-admission
      dockerfile: Dockerfile
    container_name: college_backend
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/college_admission?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: moki@amma123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: "8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - college_network

  frontend:
    build:
      context: ./Frontend/college-admission-frontend
      dockerfile: Dockerfile
    container_name: college_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - college_network

networks:
  college_network:
    driver: bridge

volumes:
  mysql_data:
