spring.application.name=grocery-delivery_db
spring.datasource.url=jdbc:mysql://localhost:3306/grocery_delivery_db
spring.datasource.username=root
spring.datasource.password=moki@amma123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081