services:

  mysql:
    image: mysql:8.0
    container_name: patient-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: moki@amma123
      MYSQL_DATABASE: patient_monitoring_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - patient-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmoki@amma123"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Backend/patient-monitoring
      dockerfile: Dockerfile
    container_name: patient-backend
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/patient_monitoring_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: moki@amma123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - patient-network

  frontend:
    build:
      context: ./Frontend/patient-monitoring-frontend
      dockerfile: Dockerfile
    container_name: patient-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - patient-network

volumes:
  mysql_data:

networks:
  patient-network:
    driver: bridge
